### PR TITLE
Update web-platform-tests expected data

### PR DESCRIPTION
**Pull request by Ms2ger**

### CODE REVIEW

**Comment by slayerjain** [comment]
@Ms2ger I'm sorry for the 'noobness', but i've no idea what this page is about.

**Comment by KiChjang** [comment]
This a pull request on top of your pull request at servo/servo#10257.

**Comment by slayerjain** [comment]
alright, so what must i do about it?

**Comment by KiChjang** [comment]
Merge this commit onto your branch, and then squash all commits in your branch into one commit.

**Comment by Ms2ger** [comment]
@slayerjain there should be a "Merge pull request" button here; click it.

**Comment by slayerjain** [comment]
I'm just confused about the intentional test it failed and how you solved it.

**Pull request merged**
